import type { Metadata } from 'next';
import './globals.css';
import { ptSansCaption } from './ui/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${ptSansCaption.className} max-w-[1400px] w-full mx-auto antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
